/*
 * TEMPO.java
 *
 * 
 */
import javax.swing.Timer; // Llamado de libreria
//import java.text.NumberFormat; // Para darle formato al numero
/**
 *
 * 
 */
public class TEMPO extends javax.swing.JFrame {
    
 Timer reloj;        // Creacion del temporizador
 Timer reloj1;
 String info;
 int l,p=0,flag=0;
 
 
 int conta = 0;
    
    
    /** Creates new form TEMPO */
    public TEMPO() {
        initComponents();
     
        
        reloj= new Timer (1000,new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVENTO_TIMER(evt);
                }
        });
        
        
        reloj1= new Timer (1000,new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVENTO_TIMER1(evt);
                }
        });
        
} 
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caja2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cajaA = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        caja1 = new javax.swing.JLabel();
        cajaB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(caja2);
        caja2.setBounds(20, 150, 150, 30);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 70, 80, 23);

        jButton2.setText("Stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(110, 70, 70, 23);

        jButton3.setText("Delay");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 110, 90, 23);
        getContentPane().add(cajaA);
        cajaA.setBounds(290, 30, 130, 40);

        jButton4.setText("Start/Stop");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(230, 90, 120, 30);

        jButton5.setText("Resset");
        getContentPane().add(jButton5);
        jButton5.setBounds(370, 90, 80, 30);
        getContentPane().add(caja1);
        caja1.setBounds(20, 30, 160, 20);
        getContentPane().add(cajaB);
        cajaB.setBounds(250, 130, 160, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-485)/2, (screenSize.height-363)/2, 485, 363);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        
        int delay = Integer.parseInt(caja2.getText());
        
        this.reloj.setDelay(delay);
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here
        
        this.reloj.stop();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        
        this.reloj.start();
        
    }//GEN-LAST:event_jButton1ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    info=cajaA.getText();
    l=info.length();
    reloj1.start();
    
    if(flag==0)
        {
            info=cajaA.getText();
            l=info.length();
            reloj1.start();
            flag=1;
        }
        else
        {
            reloj1.stop();
            flag=0;
        }
    
    
}//GEN-LAST:event_jButton4ActionPerformed
      
    public void  EVENTO_TIMER(java.awt.event.ActionEvent evt){
        
        conta++;
        caja1.setText("valor conta =  " + conta);

    
      }
    
    public void EVENTO_TIMER1 (java.awt.event.ActionEvent evt){
     
        char q;
        String f;
        if(p<l)
        {
            q=info.charAt(p);
            f=String.valueOf(q);
            cajaB.setText(cajaB.getText()+f);
            p++;
        }

        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEMPO().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caja1;
    private javax.swing.JTextField caja2;
    private javax.swing.JTextField cajaA;
    private javax.swing.JLabel cajaB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
    
}
